AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*acts_as_taggable*'
    - 'config/environments/*'
    - 'bin/*'
    - 'node_modules/**/*'

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/ExtraSpacing:
  ForceEqualSignAlignment: true

Layout/LineLength:
  Max: 120

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Metrics/AbcSize:
  Max: 25

Metrics/BlockLength:
  Exclude:
    - 'spec/features/*'
    - 'Guardfile'

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 20

Style/Documentation:
  Enabled: false

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Style/SymbolArray:
  EnforcedStyle: brackets

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

