version: '3.4'

services:
  web:
    build:
      context: .
      args:
        USERNAME: $USER
        UID: ${USER_ID:-0}
        GID: ${GROUP_ID:-0}
    command: "./script/start-dev.sh"
    volumes:
      - .:/app
      - smc-gems:/gems
      - /app/node_modules
    ports:
      - "3000:3000"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
#    user: $USER
    links:
      - db
    environment:
      DB_DEV: smc-development
      DB_HOST: db
      DB_TEST: smc-test
      DB_USERNAME: postgres
      xero_api_client_id: '26A4CA022A074485A758D9D8AF9A0E66'
      xero_api_client_secret: '72aW5Ozh96a20qLRY0dr7-_i_4Xp2PiKnyq3WYgGc-N6HnfF'

  db:
    image: postgres:11.5
    volumes:
      - smc-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"


volumes:
  smc-data:
  smc-gems: